version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: daily
    reviewers:
      - "jeremypoulter"
      - "glynhudson"
      - "chris1howell"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "jeremypoulter"
      - "glynhudson"
      - "chris1howell"
