openapi: 3.0.2
info:
  title: OpenEVSE WiFi API
  description: The API for the OpenEVSE WiFi module
  version: '1.0'
  contact:
    email: jeremy@bigjungle.net
    name: Jeremy Poulter
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: '{server}'
    variables:
      server:
        default: 'http://openevse.local'
  - url: 'http://localhost:8080'
paths:
  /status:
    get:
      operationId: getStatus
      summary: Get the status of the EVSE
      description: |
        The status endpoint can be called to get the status of the EVSE.

        While it is posible to poll this endpoint, the recomendatoin is to retrieve the initial 
        state then use the [/ws](#statusUpdates) 
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/Status.yaml
      tags:
        - Status
  /ws:
    get:
      operationId: statusUpdates
      summary: WebSocket endpoint that streams updates to the EVSE status
      description: |
        As the state changes on the EVSE a websocket frame will be sent over the socket. 
        The frame will contain a JSON document conntaining only the updated state.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/Status.yaml
      tags:
        - Status
  /config:
    get:
      operationId: getConfig
      responses:
        '200':
          $ref: '#/components/responses/UpdateSuccessful'
        '400':
          description: Bad Request
      summary: Get the EVSE configuration
      description: ''
      tags:
        - Config
    post:
      operationId: updateConfig
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/Config.yaml
      summary: Update the EVSE configuration
      tags:
        - Config
  /override:
    get:
      responses:
        '200':
          description: Manual overide is active
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Properties'
        '404':
          $ref: '#/components/responses/NotFound'
      operationId: getManualOverride
      tags:
        - Manual Override
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Properties'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
      operationId: setManualOverride
      tags:
        - Manual Override
    patch:
      description: Toggle the manual override
      responses:
        '200':
          description: OK
      operationId: toggleManualOverride
      tags:
        - Manual Override
    delete:
      description: Clears the manual override
      responses:
        '200':
          description: OK
      operationId: clearManualOverride
      tags:
        - Manual Override
  /claims:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Claim'
      operationId: listClaims
      tags:
        - Claims
  '/claims/{client}':
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Properties'
        '404':
          $ref: '#/components/responses/NotFound'
      parameters: []
      operationId: getClaim
      tags:
        - Claims
    post:
      description: Make/Update a claim
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Properties'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          $ref: '#/components/responses/BadRequest'
      operationId: setClaim
      summary: Make/Update a claim
      tags:
        - Claims
    delete:
      description: Release a claim
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '404':
          $ref: '#/components/responses/NotFound'
      operationId: releaseClaim
      summary: Release a claim
      tags:
        - Claims
    parameters:
      - schema:
          type: integer
        name: client
        in: path
        required: true
        description: 'The client ID, defined by [OpenEVSE](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/blob/master/src/evse_man.h#L25)'
  /schedule:
    get:
      summary: Get the current list of events
      description: This will get a complete list of events in the schedule
      responses:
        '200':
          description: List of the schedule events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScheduleEvent'
        '400':
          $ref: '#/components/responses/BadRequest'
      operationId: listSchedule
      tags:
        - Schedule
    post:
      operationId: updateSchedule
      description: Perform multiple event updates
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ScheduleEvent'
            examples:
              example-1:
                value:
                  - id: 1
                    state: active
                    time: '14:15:22Z'
                    days:
                      - monday
        description: Inventory item to add
      tags:
        - Schedule
      summary: Batch update schedule
  '/schedule/{id}':
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
        description: Numeric ID of the event
    get:
      summary: Get a specific event details
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleEvent'
      operationId: getScheduleEvent
      tags:
        - Schedule
    post:
      responses:
        '200':
          $ref: '#/components/responses/UpdateSuccessful'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleEvent'
        description: ''
      operationId: setScheduleEvent
      tags:
        - Schedule
    delete:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
              examples: {}
      operationId: removeScheduleEvent
      tags:
        - Schedule
components:
  schemas:
    Properties:
      title: EVSE properties
      type: object
      properties:
        state:
          $ref: '#/components/schemas/EvseState'
        auto_release:
          type: boolean
          description: |
            `true` if the manual override is auto-released when the vehicle is
            disconnected, `false` if manual override will persist after vehicle
            disconnection.
    Message:
      title: Informational message
      type: object
      properties:
        msg:
          type: string
          description: The message
    ClientId:
      title: EVSE Client ID
      type: integer
      description: 'The client ID, defined by [OpenEVSE](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/blob/master/src/evse_man.h#L25)'
    Claim:
      title: EVSE claim
      allOf:
        - type: object
          properties:
            client:
              $ref: '#/components/schemas/ClientId'
            priority:
              type: integer
              description: 'The priority of the claim, the higher the number the higher the priority'
        - $ref: '#/components/schemas/Properties'
    EvseState:
      title: EVSE state
      type: string
      enum:
        - active
        - disabled
    ScheduleEvent:
      type: object
      properties:
        id:
          type: integer
          example: 1
        state:
          $ref: '#/components/schemas/EvseState'
        time:
          type: string
          format: time
        days:
          type: array
          uniqueItems: true
          items:
            type: string
            enum:
              - monday
              - tuesday
              - wednesday
              - thursday
              - friday
              - saturday
              - sunday
      required:
        - state
        - time
        - days
      title: ''
  responses:
    UpdateSuccessful:
      description: Update successful
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Message'
          examples:
            Success message:
              value:
                msg: done
    NotFound:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Message'
          examples:
            Not found:
              value:
                msg: Not found
    BadRequest:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Message'
          examples:
            Bad JSON:
              value:
                msg: Could not parse JSON
tags:
  - name: Claims
  - name: Config
  - name: Manual Override
  - name: Schedule
  - name: Status
