# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build/Release OpenEVSE

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        env:
          - openevse_nodemcu-32s
          - openevse_esp-wrover-kit
          - openevse_esp-wrover-kit_latest
          - openevse_huzzah32_dev
          - openevse_huzzah32
          - openevse_featheresp32
          - openevse_wifi_v1
          - openevse_esp32-gateway
          - openevse_esp32-gateway-e
          - openevse_esp32-heltec-wifi-lora-v2

    steps:
    - uses: ammaraskar/gcc-problem-matcher@master

    - uses: actions/checkout@v2
      with:
        submodules: recursive

#    - name: Temp checkout latest OpenEVSE lib
#      uses: actions/checkout@v2
#      with:
#        repository: jeremypoulter/OpenEVSE_Lib
#        ref: openevse_wifi_timer_apis
#        path: lib/OpenEVSE

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Set up Node JS
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install dependencies
      run: |
        cd gui
        npm install

    - name: Build GUI
      run: |
        cd gui
        npm run build

    - name: Run PlatformIO
      run: pio run -e ${{ matrix.env }}

    - name: Upload output to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.env }}.bin
        path: .pio/build/${{ matrix.env }}/firmware.bin

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Download the built assets
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Rename images to something more sensible
      run: |
        find artifacts -name 'firmware.bin' | while read -r image; do
          dir=$(dirname "${image}")
          board=$(basename "${dir}")
          echo mv "$image" "$board"
          mv "$image" "$board"
        done

    - name: Upload assets to latest release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          *.bin
