name: PlatformIO CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Temp checkout latest OpenEVSE lib
      uses: actions/checkout@v2
      with:
        repository: jeremypoulter/OpenEVSE_Lib
        ref: openevse_wifi_timer_apis
        path: lib/OpenEVSE

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Set up Node JS
      uses: actions/setup-node@v2
      with:
        node-version: '12'

  build_gui:
    name: Build GUI
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Install dependencies
      run: |
        cd gui
        npm install

    - name: Build GUI
      run: |
        cd gui
        npm run build

  build_firmware:
    name: Build Firmware(s)
    runs-on: ubuntu-latest
    needs: build_gui
    strategy:
      fail-fast: false
      matrix:
        env:
          - openevse_nodemcu-32s
          - openevse_esp-wrover-kit
          - openevse_huzzah32_dev
          - openevse_huzzah32
          - openevse_featheresp32
          - openevse_wifi_v1
          - openevse_esp32-gateway
          - openevse_esp32-gateway-e
          - openevse_esp32-heltec-wifi-lora-v2

    steps:
    - name: Install dependencies
      run: |
        cd gui
        npm install

    - name: Build GUI
      run: |
        cd gui
        npm run build

    - name: Run PlatformIO
      run: pio run -e ${{ matrix.env }}

    - name: Upload output to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.env }}.bin
        path: .pio/build/${{ matrix.env }}/firmware.bin

